version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: busca-cep-backend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
